### ISSUE TITLE
如果使用maven就更方便了

### ISSUE THREAD

**Issue by ethanbing** [Aiden-777/EasyTron#3]
如果使用maven就更方便了
目前  org.tron. 这些都是没有发布maven的
感谢分享，大力支持

**Comment by Aiden-777** [comment]
Maven安装本地jar包引用正确方式
参考：
https://maven.apache.org/guides/mini/guide-3rd-party-jars-local.html
https://maven.apache.org/plugins/maven-install-plugin/install-file-mojo.html

例如(自行替换目录，不看源码可忽略-Dsources)：
`mvn install:install-file -Dfile="G:\local-repository\local-jar\core-0.3.0.jar" -DgroupId="org.tron.trident" -DartifactId="core" -Dversion="0.3.0" -Dpackaging="jar" -Dsources="G:\local-repository\local-jar\core-0.3.0-sources.jar"`
