### ISSUE TITLE
请问下如果我要转带有小数点的trc20，比如11.122，我应该如何修改这个测试用例？

### ISSUE THREAD

**Issue by testerSunshine** [Aiden-777/EasyTron#4]
`
// 真实金额 - 单位个
        long realAmount = 11;

        // 根据合约地址获取合约信息
        org.tron.trident.core.contract.Contract contract = wrapper.getContract(contractAddress);
        // 构造trc20合约
        Trc20Contract trc20Contract = new Trc20Contract(contract, from, wrapper);

        // trc20 合约转账
        String tid = trc20Contract.transfer(
                to,
                realAmount,
                // 精度
                trc20Contract.decimals().intValue(),
                "备注",
                // feeLimit
                Convert.toSun("50", Convert.Unit.TRX).longValue()
        );
        log.debug(tid);
`

**Comment by Aiden-777** [comment]
参考：https://github.com/Aiden-777/EasyTron/commit/313a685753667a3e44214f568a2e6e35045fd03a

**Comment by testerSunshine** [comment]
好的，谢谢
