### ISSUE TITLE
想问一下，为啥gas费用是设置的固定50个trx

### ISSUE THREAD

**Issue by lghcode** [Aiden-777/EasyTron#6]

**Comment by Aiden-777** [comment]
gas费用设置为50，实际不会消耗这么多，只是封顶限制，防止链上交易出现异常情况。
~~两年前有过提高gas费先例，给50个，至少近几年不至于因为链上调整导致需要紧急修改程序。~~
当然，实际项目中，gas费应当支持自定义，在配置文件中供用户自行设置：
https://github.com/Aiden-777/EasyTron/blob/0f761146e5724e7cc9f0221de6b7544c7a95ea5a/src/main/java/org/tron/easywork/handler/transfer/Trc20TransferHandler.java#L41-L43


同样应该支持，每笔交易设置独立的gas费：
https://github.com/Aiden-777/EasyTron/blob/0f761146e5724e7cc9f0221de6b7544c7a95ea5a/src/main/java/org/tron/easywork/handler/transfer/Trc20TransferHandler.java#L74-L83

遵循这个理念，使程序更加健壮（把锅甩出去）！
